"""初始化

Revision ID: cc2d233b2821
Revises:
Create Date: 2026-03-13 16:48:05.279846

"""

# pyright: reportAttributeAccessIssue=none
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc2d233b2821"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostgreSQL 的 trigram 索引（gin_trgm_ops）需要 pg_trgm 扩展
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("metabolic_energy", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（数据库自动生成）",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间（数据库自动生成/刷新）",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_foods_id")),
    )
    op.create_index("idx_foods_brand_name", "foods", ["brand", "name"], unique=False)
    op.create_index("idx_foods_brand_price", "foods", ["brand", "price"], unique=False)
    op.create_index(
        "idx_foods_created_at_desc",
        "foods",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_foods_foods_created_at"), "foods", ["created_at"], unique=False
    )
    op.create_index(
        op.f("idx_foods_foods_metabolic_energy"),
        "foods",
        ["metabolic_energy"],
        unique=False,
    )
    op.create_index(op.f("idx_foods_foods_name"), "foods", ["name"], unique=True)
    op.create_index(op.f("idx_foods_foods_price"), "foods", ["price"], unique=False)
    op.create_index(op.f("idx_foods_foods_weight"), "foods", ["weight"], unique=False)
    op.create_index(
        "idx_foods_updated_at_desc",
        "foods",
        [sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("variety", sa.String(length=100), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("meals_per_day", sa.Integer(), nullable=False),
        sa.Column("is_neutered", sa.Boolean(), nullable=False),
        sa.Column("is_obese", sa.Boolean(), nullable=False),
        sa.Column("activity_level", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（数据库自动生成）",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间（数据库自动生成/刷新）",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles_id")),
        sa.UniqueConstraint("name", name=op.f("uk_profiles_name")),
    )
    op.create_index(
        "idx_profiles_created_at_desc",
        "profiles",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_profiles_gender_name", "profiles", ["gender", "name"], unique=False
    )
    op.create_index(
        op.f("idx_profiles_profiles_created_at"),
        "profiles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_profiles_updated_at_desc",
        "profiles",
        [sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_profiles_variety_birthday",
        "profiles",
        ["variety", "birthday"],
        unique=False,
    )
    op.create_index(
        "idx_profiles_variety_gender", "profiles", ["variety", "gender"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（数据库自动生成）",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间（数据库自动生成/刷新）",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_id")),
    )
    op.create_index(
        op.f("idx_user_user_created_at"), "user", ["created_at"], unique=False
    )
    op.create_index(op.f("idx_user_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "accesstoken",
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_accesstoken_user_id"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_accesstoken_token")),
    )
    op.create_index(
        op.f("idx_accesstoken_accesstoken_created_at"),
        "accesstoken",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("due_date", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（数据库自动生成）",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间（数据库自动生成/刷新）",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], name=op.f("fk_reminders_profile_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders_id")),
    )
    op.create_index("idx_reminders_due_date", "reminders", ["due_date"], unique=False)
    op.create_index(
        "idx_reminders_get_by_title",
        "reminders",
        ["profile_id", "is_done"],
        unique=False,
    )
    op.create_index("idx_reminders_is_done", "reminders", ["is_done"], unique=False)
    op.create_index(
        "idx_reminders_profile_due_date",
        "reminders",
        ["profile_id", "is_done", "due_date"],
        unique=False,
    )
    op.create_index(
        "idx_reminders_profile_due_is_done",
        "reminders",
        ["profile_id", "due_date", "is_done"],
        unique=False,
    )
    op.create_index(
        "idx_reminders_profile_type", "reminders", ["profile_id", "type"], unique=False
    )
    op.create_index(
        op.f("idx_reminders_reminders_created_at"),
        "reminders",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_reminders_reminders_profile_id"),
        "reminders",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        "idx_reminders_title_gin_trgm",
        "reminders",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index("idx_reminders_type", "reminders", ["type"], unique=False)
    op.create_table(
        "weight_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("weight_g", sa.Integer(), nullable=False),
        sa.Column("measured_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（数据库自动生成）",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间（数据库自动生成/刷新）",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], name=op.f("fk_weight_records_profile_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weight_records_id")),
    )
    op.create_index(
        "idx_weight_records_get_by_profile_id",
        "weight_records",
        ["profile_id", "measured_at"],
        unique=False,
    )
    op.create_index(
        "idx_weight_records_measured_at_desc",
        "weight_records",
        [sa.literal_column("measured_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_weight_records_weight_records_created_at"),
        "weight_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_weight_records_weight_records_profile_id"),
        "weight_records",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_weight_records_weight_records_profile_id"),
        table_name="weight_records",
    )
    op.drop_index(
        op.f("idx_weight_records_weight_records_created_at"),
        table_name="weight_records",
    )
    op.drop_index("idx_weight_records_measured_at_desc", table_name="weight_records")
    op.drop_index("idx_weight_records_get_by_profile_id", table_name="weight_records")
    op.drop_table("weight_records")
    op.drop_index("idx_reminders_type", table_name="reminders")
    op.drop_index(
        "idx_reminders_title_gin_trgm",
        table_name="reminders",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(op.f("idx_reminders_reminders_profile_id"), table_name="reminders")
    op.drop_index(op.f("idx_reminders_reminders_created_at"), table_name="reminders")
    op.drop_index("idx_reminders_profile_type", table_name="reminders")
    op.drop_index("idx_reminders_profile_due_is_done", table_name="reminders")
    op.drop_index("idx_reminders_profile_due_date", table_name="reminders")
    op.drop_index("idx_reminders_is_done", table_name="reminders")
    op.drop_index("idx_reminders_get_by_title", table_name="reminders")
    op.drop_index("idx_reminders_due_date", table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(
        op.f("idx_accesstoken_accesstoken_created_at"), table_name="accesstoken"
    )
    op.drop_table("accesstoken")
    op.drop_index(op.f("idx_user_user_email"), table_name="user")
    op.drop_index(op.f("idx_user_user_created_at"), table_name="user")
    op.drop_table("user")
    op.drop_index("idx_profiles_variety_gender", table_name="profiles")
    op.drop_index("idx_profiles_variety_birthday", table_name="profiles")
    op.drop_index("idx_profiles_updated_at_desc", table_name="profiles")
    op.drop_index(op.f("idx_profiles_profiles_created_at"), table_name="profiles")
    op.drop_index("idx_profiles_gender_name", table_name="profiles")
    op.drop_index("idx_profiles_created_at_desc", table_name="profiles")
    op.drop_table("profiles")
    op.drop_index("idx_foods_updated_at_desc", table_name="foods")
    op.drop_index(op.f("idx_foods_foods_weight"), table_name="foods")
    op.drop_index(op.f("idx_foods_foods_price"), table_name="foods")
    op.drop_index(op.f("idx_foods_foods_name"), table_name="foods")
    op.drop_index(op.f("idx_foods_foods_metabolic_energy"), table_name="foods")
    op.drop_index(op.f("idx_foods_foods_created_at"), table_name="foods")
    op.drop_index("idx_foods_created_at_desc", table_name="foods")
    op.drop_index("idx_foods_brand_price", table_name="foods")
    op.drop_index("idx_foods_brand_name", table_name="foods")
    op.drop_table("foods")
    # ### end Alembic commands ###
